### ISSUE TITLE
list index out of range error

### ISSUE THREAD

**Issue by jasonkgreen** [jdevoo/twecoll#12]
I get this in the midst of a fetch.  Not sure if it's a python error or a twecoll error.

**Comment by lucahammer** [comment]
This happens when there is an empty line in the .dat file. I am not sure yet when they happen but a quick fix is to remove the empty line and start the fetch command again.

**Comment by jasonkgreen** [comment]
Thanks. This seems to have solved it.

**Comment by jdevoo** [comment]
Thank you @lucahammer ! I wonder how these empty lines come about... Any chance you can share the handle to reproduce this @jasonkgreen ?

**Comment by lucahammer** [comment]
For the first time I was able to reproduce the error. It's probably something in the location field. Example of an account where the error happens: https://twitter.com/Atomroflbomber

**Comment by lucahammer** [comment]
I am testing `location = data['location'].strip()` in [line 399](https://github.com/jdevoo/twecoll/blob/master/twecoll#L399) as a fix. Didn't have the problem again, but will test it some more before submitting a PR. I wonder if there are cases where it doesn't work because the problematic characters are surrounded by the location text. Then it would be better to replace \n and \t.

**Comment by lucahammer** [comment]
As expected it wasn't enough. This account triggered another out of range error: https://twitter.com/luXus_Suizid.

I added the following as a workaround. 
`       location = location.replace('\n', ' ')
        location = location.replace('\t', ' ')`

**Comment by jdevoo** [comment]
cool - we can probably chain them into a [single line](http://stackoverflow.com/questions/3411771/multiple-character-replace-with-python#27086669)... wonder if this needs to be applied to other attributes as well

**Comment by jdevoo** [comment]
made the change but left out the tab case.
