### ISSUE TITLE
empty search query

### ISSUE THREAD

**Issue by jdevoo** [jdevoo/twecoll#22]
`twecoll tweets -q "nntaleb AND doctrine"` does not return anything but web interface shows results

**Comment by lucahammer** [comment]
"AND" is not an official search operator for the API (https://dev.twitter.com/rest/public/search). It's the default setting for the API that all keywords have to be in the tweet. But that isn't the problem. 

The problem is that the search API only goes back 7 days (in my experience it's 10 days in most cases). 

There is a scraper which uses the web search to get older tweets but it isn't really satisfying: https://github.com/Jefferson-Henrique/GetOldTweets-python

Another way is to pay Twitter through Gnip for access to older tweets. https://gnip.com/historical/

**Comment by jdevoo** [comment]
Thank you @lucahammer !
