### ISSUE TITLE
Increase cursor count?

### ISSUE THREAD

**Issue by aaeissa** [jdevoo/twecoll#33]
Is there a way to increase the "count" of what the cursor returns?

I've mainly used the Tweepy library in the past, but trying out Twecoll for a project now.

The call in Tweepy and other Twitter API wrappers is something like:  

> tweepy.Cursor(api.followers, screen_name='username', count=200).items()  

which allows the cursor to return 3000 users before having to wait 15 minutes for the rate limit. 

I tried using Twecoll to go through an account with ~15k followers . 
 
> python twecoll init screename -o . 
> python twecoll fetch screename . 

but it would *only* pull 15 users at a time (when fetching) and thus take days/weeks for the 15k followers.

**Comment by lucahammer** [comment]
The init command collects information about the users. In the case of followers it gets the list of follower IDs and uses the lookup-endpoint to collect information of 100 users per API-call, which is the maximum for that endpoint: https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-lookup

The fetch command iterates over all accounts (followers in this case) to get their followings. The used friends/ids endpoint returns 5000 IDs per call. Per default users that follow more than 5000 people are skipped. With 15k followers this means it needs 15k calls. At 15 calls per 15 minutes, it takes about 11 days to collect them all. https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friends-ids

The tweepy call you quoted only requests 200 IDs instead of 5000. So it would take even longer. Though you could change the count to 5000 as well.

I hope I was able to make it clearer how the different commands work.

**Comment by HoneyPasricha** [comment]
when i tried to fetch the followers of followers it took just 280 followers from first coming followers per call using the tweepy
there is an another issue when it fetched from the twitter it take time to response to fetch the followers 
i want collection of 10000 followers list for research work please suggest me 
what should i do to increase the number of followers?
