### ISSUE TITLE
fetch command

### ISSUE THREAD

**Issue by antongiac** [jdevoo/twecoll#35]
Hello, 
I want to study some hashtags during a certain week. Since I want fo study multiple hashtags I will not be able to run the fetch command during that week, due to the API requests limitations. My question is: if I run the init command referred to the hashtags, will I be then able to run the fetch command in a second time? In other words does the fetch command refers to the .dat file generated by the init command? Moreover, if it does there is a time limit for me to start the fetch command to make it refer to the desired week? 
thanks in advance and for the marvelous script

**Comment by lucahammer** [comment]
Yes, you can run the commands at separate times.

## twecoll tweets -q '#hashtag'
Collects the tweets and generates a .twt-file.

## twecoll init -q '#hashtag'
Extracts the twitter handles from the .twt-file and populates a .dat-file with information about the accounts.

## twecoll fetch '#hashtag'
Goes through the .dat-file and generates for each account a file in a subdirectory with the IDs the account follows. 

Only the 'tweets'-command must be run in time, because the Twitter search API is limited to the last 7-10 days. The other commands can be run later. With one caveat. The collected profile data and follow data will be from the moment when the command is run. In most cases this no problem because people seldom or only slowly change their name/followings.

**Comment by jdevoo** [comment]
in addition to what Luca said, I also use diff to identify overlaps between two eg fetch runs and consolidate unique lines into a separate file.

**Comment by diegodorgam** [comment]
Hi guys, 
I keep getting a error in fetch 
`<urlopen error [Errno 110] Connection timed out>`
any ideas?

**Comment by jdevoo** [comment]
still not found a solution for this; see also #5
