### ISSUE TITLE
[QUESTION] Does Twecoll 'init' work for large accounts?

### ISSUE THREAD

**Issue by hudmb** [jdevoo/twecoll#55]
Hi,

Does Twecoll 'init' work for large accounts, e.g. @ManUtd which has 18.2M Followers? I'm looking for an efficient method of downloading all the follower IDs for some large accounts?

**Comment by lucahammer** [comment]
The init command first gets all IDs (5k per call) and then the info of the accounts (100 per call). The IDs are only in memory, not on disk.

At the current [rate limits](https://developer.twitter.com/en/docs/basics/rate-limits.html) of 15 calls per 15 minutes will take about three days running non-stop to only get the IDs. Another 19 weeks to collect the info on each account.

twecoll is not prepared to collect the IDs only, but you could rewrite it that the bag with the IDs is written to a file instead of using it to get the data on the accounts. https://github.com/jdevoo/twecoll/blob/master/twecoll#L347

**Comment by hudmb** [comment]
Thank you! Very useful :)

**Comment by watty62** [comment]
Hi @hudmb (and @lucahammer ) if all you want is a list followers, I found this https://github.com/aspiringguru/twitterDataAnalyse/blob/master/get_twitter_followers_of_nominated_user.py to be very useful.

**Comment by hudmb** [comment]
Thank you!

**Comment by hudmb** [comment]
@watty62 Thanks for this tip. Quick question about the keys.py file. What should it look like? I just created a keys.py and put this in it (I've changed the keys): -

CONSUMER_KEY = keys['cJpMV27ABpBIT20nB2AsqYC52']
CONSUMER_SECRET = keys['jWA0HbRKVebsuot2qOuvLA2LCTHioqiWByekvRM3ZrYHiG866O']
```
ACCESS_TOKEN = keys['17654433-d1fqdfDhD2Oc22W5au0d3kjjEYXXHKchRQKpSKtvo']
ACCESS_TOKEN_SECRET = keys['82pKGX4PLotSnaShCDiNn9gr48qPylh9dlauj9StsLa4w']
auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)
```

Sorry - as I'm not a programmer I don't know how to do this part. If you could help, I'd appreciate it.

Thanks!

**Comment by jdevoo** [comment]
I'll close this @hudmb as it is tweepy related.
